### ISSUE TITLE
Deployment of website to git pages

### ISSUE THREAD

**Issue by lengushuru** [lengushuru/portfolio-website#6]
**Below is the link to portolio-website live demo** 

- https://lengushuru.github.io/portfolio-website/

**Comment by brainconnect93** [comment]
## Status: Approved :heavy_check_mark:

Hi @lengushuru, 👋 

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://media.tenor.com/ipGxBQElNzYAAAAM/approved-ymaz.gif" width="500px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

### Changes Required ♻️

- [x]  _Please check the comments under the review._

### Optional Changes 🔥

Thank You.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
